name: CI pipeline
on:
    push:
        branches:
            - main
env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
jobs:
    CI:
        name: Continuous integration
        runs-on: ubuntu-22.04
        defaults:
            run:
                working-directory: ./DRFProject
        services:
            postgresDB:
              image: postgres:16-alpine
              env:
                  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
              ports:
                - 5432:5432
              options: >-
                --health-cmd pg_isready
                --health-retries 15
                --health-interval 1s
        steps:
            - name: Pulling repository
              uses: actions/checkout@v4.1.7
              with:
                repository: Nikilandgelo/online_store_backend
            - name: Install Python
              uses: actions/setup-python@v5.2.0
              with:
                python-version: 3.12
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run Linter
              run: >-
                flake8 .
                --exclude=**/migrations/*,.venv/*,**/settings.py,**/html_forms.py,**/apps.py
            - name: Run Tests with coverage
              run: pytest --cov=.
